NDefines.NGame.START_DATE = "1857.07.18"
NDefines.NGame.END_DATE = "1925.01.02"
NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 4.905
NDefines.NGame.MAJOR_PARTICIPANTS_FOR_MAJOR_WAR = 2
NDefines.NGame.FUEL_RESOURCE = "resource_food"
NDefines.NGame.MAX_SCRIPTED_LOC_RECURSION = 60
NDefines.NGame.HANDS_OFF_START_TAG = "EUR"

NDefines.NCountry.BASE_RESEARCH_SLOTS = 1
NDefines.NCountry.POPULATION_YEARLY_GROWTH_BASE = 0.005

NDefines.NProduction.MAX_EQUIPMENT_RESOURCES_NEED = 6
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 5
NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 25